### ISSUE TITLE
wsdl2py generates invalid code

### ISSUE THREAD

**Issue by lociii** [FlightDataServices/soapfish#11]
wsdl2py -c http://www.matelso.de/Partnerbereich/Matelso_MRS_v_2_0.asmx?WSDL
generates invalid python code

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import client
  File "/home/jni/projects/soap/client.py", line 19, in <module>
    class Create_subscriber(xsd.ComplexType):
  File "/home/jni/projects/soap/client.py", line 24, in Create_subscriber
    partner_id = xsd.ListElement(xsd.String, minOccurs=0, maxOccurs=1)
TypeError: __init__() takes at least 3 arguments (4 given)

the "tagname" parameter is missing when instantiating xsd.ListElement

**Comment by FelixSchwarz** [comment]
just wanted to mention that the python code generated by soapfish seems to work fine (at least I can import it without syntax error): `partner_id = xsd.Element(xsd.String, minOccurs=0)`

**Comment by pope1ni** [comment]
I can confirm that this works in soapfish but was broken in the legacy soapbox project.
