### ISSUE TITLE
Dispatcher not working with Django 1.7+

### ISSUE THREAD

**Issue by vahidm** [FlightDataServices/soapfish#26]
Hi,

We know [mimetype is removed in django 1.7] (https://docs.djangoproject.com/en/1.8/internals/deprecation/#deprecation-removed-in-1-7) from HttpResponse objects, but it is still used in `get_django_dispatch` and causes a TypeError in runtime. I think it needs to be changed to `content_type`.

**Comment by FelixSchwarz** [comment]
You might want to check my soapbox fork (with many contributions from others!): https://github.com/FelixSchwarz/soapfish
I just merged support for Django 1.9 (and there are automated Travis tests so we don't break stuff too often).

**Comment by pope1ni** [comment]
Should have been solved by Felix. Closing...
