### ISSUE TITLE
wsdl2py — ValueError: Unicode strings with encoding declaration are not supported

### ISSUE THREAD

**Issue by RealJTG** [FlightDataServices/soapfish#29]
```
> wsdl2py.exe -c http://services.rs.ge/WayBillService/WayBillService.asmx?WSDL
Traceback (most recent call last):
  File "D:\repo\rs.ge\venv\Scripts\wsdl2py-script.py", line 9, in <module>
    load_entry_point('soapfish==0.6dev', 'console_scripts', 'wsdl2py')()
  File "D:\repo\rs.ge\venv\lib\site-packages\soapfish\wsdl2py.py", line 112, in main
    code = generate_code_from_wsdl(xml, target, opt.use_wsa, cwd=cwd)
  File "D:\repo\rs.ge\venv\lib\site-packages\soapfish\wsdl2py.py", line 64, in generate_code_from_wsdl
    xmlelement = etree.fromstring(xml)
  File "lxml.etree.pyx", line 3103, in lxml.etree.fromstring (src\lxml\lxml.etree.c:70569)
  File "parser.pxi", line 1823, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:106368)
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.
```
Can be fixed by adding `xml.encode(encoding)` at [wsdl2py.py#L64](https://github.com/FlightDataServices/soapfish/blob/a9f6c4c721d0dd22aa35d42f046d225cb1bbabb8/soapfish/wsdl2py.py#L64) but I'm not quite sure what's actually happening there, because if you save file locally and run `wsdl2py.exe -c WayBillService.wsdl` it works fine.

Jinja2==2.8
MarkupSafe==0.23
argparse==1.4.0
lxml==3.4.4
pythonic-testcase==1.2.1
requests==2.9.1
six==1.10.0
soapfish==0.6dev

**Comment by FelixSchwarz** [comment]
I can reproduce the issue. Basically we're passing unicode (or in Python 3: a string) to etree.fromstring and lxml doesn't like that. I don't want to reuse the "encoding" parameter but we should be able to use utf-8 as default.
Until we have a proper fix in the code your workaround should be good enough.

Thank you very much for reporting + debugging the issue.

**Comment by FelixSchwarz** [comment]
Ah, I just noticed that you filed this report in the "old" project managed by FlightDataServices (I just wondered why I can't add labels here...). This repo has been officially retired, please use my repo (https://github.com/FelixSchwarz/soapfish/) and file your bug report there. I can't ensure I'll remember this bug report if it is only filed here...

**Comment by RealJTG** [comment]
Done https://github.com/FelixSchwarz/soapfish/issues/82

**Comment by pope1ni** [comment]
Closed.
