### ISSUE TITLE
No templates directory

### ISSUE THREAD

**Issue by happycorsair** [FlightDataServices/soapfish#30]
Thank you for your project, it's awesome!

Fresh installation by pip brings no "templates" directory, so issue #4 can be re-opened.

**Comment by pope1ni** [comment]
Hi,

We have discontinued the original soapbox project and it has been replaced by [soapfish](https://github.com/soapteam/soapfish) which is now maintained by a small group of people who use the project. There have been many fixes and improvements to the project and we are still trying to work towards a new release - see the [milestone](https://github.com/soapteam/soapfish/milestone/1) for outstanding issues to be fixed.

We recommend that you use the latest git master until v0.6.0 is released.
