### ISSUE TITLE
xsd2py uses wrong default for attribute use flag

### ISSUE THREAD

**Issue by oskrkal** [FlightDataServices/soapfish#32]
According to the [W3C XML Schema Definition Language document](https://www.w3.org/TR/xmlschema11-1/#declare-attribute), the default value for _use_ attribute of _xsd:attribute_ element is _optional_. However, the _use_ member of _Attribute_ class in xsd module defaults to _Use.REQUIRED_. If _use_ attribute is missing on an attribute definition in XSD file, _xsd2py_ omits it also in the generated python file, and thus, leaves it set to the incorrect default value.

There are two possible fixes:

1. changing the default value of _use_ member in the _Attribute_ class to _Use.OPTIONAL_, or
2. updating xsd2py to always set the _use_ member explicitly and according to the standard.

**Comment by oskrkal** [comment]
Commit 3885c50 in pull request #31 fixes the issue using solution 2.

**Comment by pope1ni** [comment]
PR #31 migrated to soapteam/soapfish#100.
