### ISSUE TITLE
ssl mutual autentication 

### ISSUE THREAD

**Issue by luisza** [FlightDataServices/soapfish#34]
Hi, i have to connect my soap client with server that implement mutual autentication over ssl.  I check the code and see that you use requests that have this feature, so in my local development i made the modification and works.  But I am asking me if it's the best option to pass ssl conf throug os environment or include and optional variables to stub object or bouth.

**Comment by pope1ni** [comment]
Closing as this was submitted as soapteam/soapfish#114.
