### ISSUE TITLE
NotImplementedError: Unable to handle embedded type error

### ISSUE THREAD

**Issue by divick** [FlightDataServices/soapfish#37]
I am trying to generate python code from wsdl but I get this error. It seems it is not implemented. In the code too I see the following comment:

**FIXME: Determine how to handle embedded types...** 

Is there a way it can be fixed easily or is it substantial work?

**Comment by FelixSchwarz** [comment]
I think you should file bugs in the actual "upstream" repository: https://github.com/soapteam/soapfish/issues

(Unfortunately with regards to your question I can not answer this from the top of my head. I suspect it is not trivial but might not be a huge task.)

**Comment by pope1ni** [comment]
Closing per https://github.com/FlightDataServices/soapfish/issues/37#issuecomment-412025236. Please file this in the correct issue tracker..
